### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by tomganleylee** [jhansche/ha-teslafi#15]
Hi, I have followed the instructions to setup via HACS, that all went smoothly but when I try to create the integration, using my API key I get the following error in the log.

I am running home assistant core 2023.12.2 
This looks like a great integration but cant work out the error. 

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 22:34:35 (1 occurrences)
Last logged: 22:34:35

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 422, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_finish_flow
    title=result["title"],
          ~~~~~~^^^^^^^^^
KeyError: 'title'

**Comment by jhansche** [comment]
It looks like there should have been another error logged before that. Can you check your logs again around the same timestamp as this one (`22:34:35`)?

Also from the TeslaFi API settings screen, confirm that you can click on the link at the bottom and see data for your car, and that the token in the URL matches the API token you're pasting in the config flow (just the token itself, not the rest of the URL)

**Comment by jhansche** [comment]
@tomganleylee anything?

**Comment by tomganleylee** [comment]
Hi, 
thanks for getting back to me, sorry in my slow response. 

i tried again after clearing the logs. and generating a new API token. What is strange is we have 2 Tesla's and 2 Teslafi accounts, the 2nd account was added in with no problem. It is just mine. i have attached all the logs that came up when i tried to add it. 

I clicked the link and it showed data, I had previously added data from teslafi into home assistant using a rest sensor and that was working fine, however, for some reason, not all the data is there now. I don't know if this is a teslafi issues.

is there another log I should be checking?


Log Details (ERROR)
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 23:08:14 (1 occurrences)
Last logged: 23:08:14

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 422, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_finish_flow
    title=result["title"],
          ~~~~~~^^^^^^^^^
KeyError: 'title'

**Comment by jhansche** [comment]
Can you check:
1. What version of the TeslaFi integration you have installed from HACS?
2. Try enabling debug logging for the integration (you can enable debug logging from the first car that was added successfully) and then try adding the 2nd car. It should add some additional information to the logs, including API responses.

If that doesn't yield additional info, you could try copying the JSON response you get when you click the link from the TeslaFi API Settings screen (obfuscate if you'd like). I'm interested in trying to reproduce the scenario that would lead to the config flow response having no title.

**Comment by tomganleylee** [comment]
Sure thank you :

1) v2.2 (HACS says it is up to date)
2) it didn't seem to gain any additional info in the logs



Log Details (ERROR)
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 23:33:50 (1 occurrences)
Last logged: 23:33:50

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 422, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_finish_flow
    title=result["title"],
          ~~~~~~^^^^^^^^^
KeyError: 'title'

the link gives this, which is odd as when i read the data from home assiant i get a lot of data, not sure if its different data though>?

{"data_id":351****,"Date":"2023-12-17 23:40:32","calendar_enabled":"502","remote_start_enabled":null,"vehicle_id":null,"display_name":null,"color":null,"fast_charger_brand":null,"notifications_enabled":null,"vin":null,"conn_charge_cable":null,"id":null,"charge_port_cold_weather_mode":null,"id_s":null,"state":"offline","option_codes":null,"user_charge_enable_request":null,"time_to_full_charge":null,"charge_current_request":null,"charge_enable_request":null,"charge_to_max_range":null,"charger_phases":null,"battery_heater_on":null,"managed_charging_start_time":null,"battery_range":null,"charger_power":null,"charge_limit_soc":null,"charger_pilot_current":null,"charge_port_latch":null,"battery_current":null,"charger_actual_current":null,"scheduled_charging_pending":null,"fast_charger_type":null,"usable_battery_level":null,"motorized_charge_port":null,"charge_limit_soc_std":null,"not_enough_power_to_heat":null,"battery_level":null,"charge_energy_added":null,"charge_port_door_open":null,"max_range_charge_counter":null,"charge_limit_soc_max":null,"ideal_battery_range":null,"managed_charging_active":null,"charging_state":null,"fast_charger_present":null,"trip_charging":null,"managed_charging_user_canceled":null,"scheduled_charging_start_time":null,"est_battery_range":null,"charge_rate":null,"charger_voltage":null,"charge_current_request_max":null,"eu_vehicle":null,"charge_miles_added_ideal":null,"charge_limit_soc_min":null,"charge_miles_added_rated":null,"inside_temp":null,"longitude":null,"heading":null,"gps_as_of":null,"latitude":null,"speed":null,"shift_state":null,"seat_heater_rear_right":null,"seat_heater_rear_left_back":null,"seat_heater_left":null,"passenger_temp_setting":null,"is_auto_conditioning_on":null,"driver_temp_setting":null,"outside_temp":null,"seat_heater_rear_center":null,"is_rear_defroster_on":null,"seat_heater_rear_right_back":null,"smart_preconditioning":null,"seat_heater_right":null,"fan_status":null,"is_front_defroster_on":null,"seat_heater_rear_left":null,"gui_charge_rate_units":null,"gui_24_hour_time":null,"gui_temperature_units":null,"gui_range_display":null,"gui_distance_units":null,"sun_roof_installed":null,"rhd":null,"remote_start_supported":null,"homelink_nearby":null,"parsed_calendar_supported":null,"spoiler_type":null,"ft":null,"odometer":null,"remote_start":null,"pr":null,"climate_keeper_mode":null,"roof_color":null,"perf_config":null,"valet_mode":null,"calendar_supported":null,"pf":null,"sun_roof_percent_open":null,"third_row_seats":null,"seat_type":null,"api_version":null,"rear_seat_heaters":null,"rt":null,"exterior_color":null,"df":null,"autopark_state":null,"sun_roof_state":null,"notifications_supported":null,"vehicle_name":null,"dr":null,"autopark_style":null,"car_type":null,"wheel_type":null,"locked":null,"center_display_state":null,"last_autopark_error":null,"car_version":null,"defrost_mode":null,"autopark_state_v2":null,"is_preconditioning":"","inside_tempF":"","driver_temp_settingF":"","outside_tempF":"","battery_heater":"","Notes":"Offline Asleep","odometerF":"","idleNumber":0,"sleepNumber":4016,"driveNumber":0,"chargeNumber":0,"polling":"","idleTime":0,"maxRange":"309.95","left_temp_direction":null,"max_avail_temp":null,"is_climate_on":null,"right_temp_direction":null,"min_avail_temp":null,"is_user_present":null,"in_service":null,"valet_pin_needed":null,"charge_port_led_color":null,"timestamp":null,"power":null,"side_mirror_heaters":null,"wiper_blade_heater":null,"steering_wheel_heater":null,"elevation":"","sentry_mode":"","fd_window":"","fp_window":"","rd_window":"","rp_window":"","measure":"imperial","temperature":"C","currency":"\u00a3","carState":"Sleeping","location":"Home","rangeDisplay":"rated","newVersion":" ","newVersionStatus":""}

**Comment by tomganleylee** [comment]
One thing i have just noticed is that teslafi, doesn't seem to see what my car's name is and is just blank where the name is on the fleet management page

**Comment by tomganleylee** [comment]
Working now!!

After seeing noname at all, i went a set the name back., (unsure why the name field was empty, and not what i called the car)
but it is now added!!!

thank you for your help, wouldn't have worked that out alone

![image](https://github.com/jhansche/ha-teslafi/assets/14944091/41815d77-a7a3-445f-9e64-b9e7b766035d)

**Comment by jhansche** [comment]
Yeah that json doesn't have any data that we need: namely `vin` and `display_name` are the bare minimum.

Glad you got it sorted out, but super strange that it behaved this way.

I wonder if maybe something about it being asleep was breaking it 🤔 like maybe what fixed it might have been waking the car. In your json the only actual usable data I can see is that the car state is "Sleeping".
